//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodInventory
    {
        public int BInventory_Id { get; set; }
        public int BI_UserId { get; set; }
        public string Blood_Group { get; set; }
        public int BI_Quantity { get; set; }
        public string BI_Bag_Code { get; set; }
        public System.DateTime BI_Date { get; set; }
    
        public virtual User User { get; set; }
    }
}
